[phases.setup]
nixPkgs = []

[phases.install]
cmds = [
    "pip install -r requirements.txt",
    "playwright install --with-deps chromium"
]

[start]
cmd = "gunicorn app:app --bind 0.0.0.0:$PORT --timeout 120 --workers 1"